package dev.qynl.backrooms.registry;

import dev.qynl.backrooms.BackroomsMod;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;

/** Every sound the mod can play. Waveforms are generated by {@code tools/gen_audio.py}. */
public final class ModSoundEvents {

    public static final SoundEvent BUZZ = register("buzz");
    public static final SoundEvent HUM = register("hum");
    public static final SoundEvent DRIP = register("drip");
    public static final SoundEvent CARPET_STEP = register("carpet_step");
    public static final SoundEvent CARPET_PLACE = register("carpet_place");
    public static final SoundEvent CARPET_BREAK = register("carpet_break");
    public static final SoundEvent DISTANT_NOISE = register("distant_noise");
    public static final SoundEvent WALL_SOUND = register("wall_sound");
    public static final SoundEvent PHANTOM_FOOTSTEP = register("phantom_footstep");
    public static final SoundEvent FLICKER = register("flicker");
    public static final SoundEvent THUMP = register("thump");
    public static final SoundEvent TEAR_AMBIENT = register("tear_ambient");
    public static final SoundEvent LISTENER_IDLE = register("listener_idle");
    public static final SoundEvent LISTENER_CHASE = register("listener_chase");
    public static final SoundEvent LISTENER_STEP = register("listener_step");

    private static SoundEvent register(String id) {
        Identifier ident = Identifier.of(BackroomsMod.MOD_ID, id);
        return Registry.register(Registries.SOUND_EVENT, ident, SoundEvent.of(ident));
    }

    private ModSoundEvents() {
    }
}
